apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: tekton-route
  namespace: tekton
spec:
  parentRefs:
    - name: pod-gateway
      sectionName: https-listener
      kind: Gateway
  hostnames:
    - "tekton.pod.nvtc.io"
  rules:
    - backendRefs:
        - name: tekton-dashboard
          port: 9097
