apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pod
  namespace: argocd
spec:
  destination:
    namespace: pod
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: false
    path: setup/components
    repoURL: https://github.com/NovatecConsulting/POD
    targetRevision: develop
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
